version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Clever/microplane
    docker:
      - image: circleci/golang:1.12-stretch
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    steps:
      - add_ssh_keys:
          fingerprints:
            - "8e:93:7e:53:e8:0e:72:4f:f1:9c:0f:50:66:55:5e:f1" # GitLab
      - run:
          command: cd $HOME && git clone --depth 1 -v https://github.com/Clever/ci-scripts.git && cd ci-scripts && git show --oneline -s
          name: Clone ci-scripts
      - checkout
      - run:
          command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
          name: Set up CircleCI artifacts directories
      - run: make install_deps
      - run: make build
      - run:
          command: make test
          environment:
            GITHUB_API_TOKEN: x
            GITLAB_API_TOKEN: "" # both cannot be set
      - run:
          command: ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts && ./gitlab_integration_test.sh
      - run: if [ "${CIRCLE_BRANCH}" == "master" ]; then make release && $HOME/ci-scripts/circleci/github-release $GH_RELEASE_TOKEN release; fi;
